name = "musical-em-bom-portugues"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

# Configurações específicas para Pages
[env.production]
name = "musical-em-bom-portugues"
vars = { ENVIRONMENT = "production" }