// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlrcvvaneofcpncbqjyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscmN2dmFuZW9mY3BuY2JxanlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTI2OTksImV4cCI6MjA2NDU2ODY5OX0.6INx0-00zPX7BW8yea8cAVNfniiGc9Y2tDMPZx2w5hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);